ARG TAG=9
FROM almalinux:${TAG}
#RUN cat /etc/*release
ARG COURSE=Docker
ARG TRAINER=munna
ENV Duration=120hrs
RUN echo "Course is: ${COURSE}, Trainer is: ${TRAINER}, Duration is: ${Duration}"
CMD [ "sleep","80"]
